apiVersion: v1
kind: Pod
metadata:
  name: some-pod
spec:
  containers:
  - name: some-container
    image: nginx
    resources:
      limits:
        cpu: "2"
        memory: "1024Mi"
      requests:
        cpu: "1"
        memory: "512Mi"